set NATIVE_MESSAGING_MANIFEST_JSON_LOCATION_HKCU="HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\keep_living_in_the_past_man"
set NATIVE_MESSAGING_MANIFEST_JSON_LOCATION_HKLM="HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts\keep_living_in_the_past_man"

set APPLICATION_HOST_NAME="keep_living_in_the_past_man"

cd /D "%~dp0"
set ADDRESS_OF_JSON=%~dp0%keep_living_in_the_past_man.json
echo "%ADDRESS_OF_JSON%"
REG delete %NATIVE_MESSAGING_MANIFEST_JSON_LOCATION_HKCU% /va /f
REG delete %NATIVE_MESSAGING_MANIFEST_JSON_LOCATION_HKLM% /va /f

REG ADD %NATIVE_MESSAGING_MANIFEST_JSON_LOCATION_HKCU% /ve /d %ADDRESS_OF_JSON% /f
REG ADD %NATIVE_MESSAGING_MANIFEST_JSON_LOCATION_HKLM% /ve /d %ADDRESS_OF_JSON% /f

pause